#!/usr/bin/env python
import click

@click.group()
def cli():
    pass

@cli.command()
def test():
    click.echo('hi!')

@cli.group(name='travel-checklist')
def travel_checklist():
    pass

@travel_checklist.command()
@click.option('--file', 
              help='json or yaml file with specification of checklist')
def create(file):
    '''If no --file specified, prompt the user interactively to get the params'''
    if file is None:
        click.echo('need to interactively prompt the user for a bunch of stuff now'
    # Prompt the user, etc...
    click.echo('template')

if __name__ == '__main__':
    cli()
